### ISSUE TITLE
`envyable install` error - Cannot load  ./lib/envyable/cli

### ISSUE THREAD

**Issue by B-raw** [philnash/envyable#11]
Ran envyable install got the following error:
```
/Users/michael/.rvm/gems/ruby-2.3.1/gems/envyable-1.1.0/bin/envyable:4:in `require': cannot load such file -- ./lib/envyable/cli (LoadError)
	from /Users/michael/.rvm/gems/ruby-2.3.1/gems/envyable-1.1.0/bin/envyable:4:in `<top (required)>'
	from /Users/michael/.rvm/gems/ruby-2.3.1/bin/envyable:23:in `load'
	from /Users/michael/.rvm/gems/ruby-2.3.1/bin/envyable:23:in `<main>'
	from /Users/michael/.rvm/gems/ruby-2.3.1/bin/ruby_executable_hooks:15:in `eval'
	from /Users/michael/.rvm/gems/ruby-2.3.1/bin/ruby_executable_hooks:15:in `<main>'
```

Changed file `bin/envyable` to `require_relative "../lib/envyable/cli"` (had been `require "./lib/envyable/cli"`)

`envyable install` now working...

Not sure why this happened, because when I cloned the repo and went to edit the code to fix it, it seems someone has very sensibly put `require File.expand_path('../lib/envyable/cli', __dir__)`

Is `gem install envyable` installing an old version of the gem?? Confused...

**Comment by philnash** [comment]
Seems that way. You need envyable version 1.1.1 which fixed that issue.

Are you installing via bundler? Do you need to run `bundle update envyable`?
