### ISSUE TITLE
Option to load variables earlier for other gems that require them

### ISSUE THREAD

**Issue by mikelkew** [philnash/envyable#5]
Hi! We have another gem that requires some ENV variable to be set before it is loaded.

The dotenv gem gives an option of specifying `, :require => 'dotenv/rails-now'` in the gemfile to load them earlier.. Was just wondering if you can think of a similar way of achieving this with envyable? If not, could you please consider adding it?

**Comment by philnash** [comment]
Hey @mikelkew, that is a good question, thanks. There is nothing like that built in to Envyable right now, but we could add this. It would be very similar to dotenv's solution, a different file to require that would perform the load as soon as the rest of the library is loaded.

**Comment by chrisnicola** [comment]
It seems to be the ENV variables should be loaded before the application initializes. Right now ENV values are not available when handling any configuration in `application.rb` which isn't what I would expect.

I've added explicit load calls to this file to compensate for this now.

**Comment by philnash** [comment]
Thanks for the input, this has been included now with @mikelkew's PR #6.
